#table(columns: (1fr, 4fr), stroke: none, fill: none,
    [AEON],    [Almost-Exact Oracle Network],
    [BASIL],   [Bayesian Astro-Symbolic Inference Layer],
    [CATS],    [Cosmic Alignment Transformer System],
    [DRIP],    [Diffusion for Ritualistic Inference Protocols],
    [EEL],     [Entangled Evidence Learner],
    [FABLE],   [Fictional Abduction Benchmark for Latent Evidence],
    [GLOW],    [Galactic Likelihood Optimizer Workflow],
    [HALO],    [Hierarchical Astral Latent Operator],
    [ION],     [Interdimensional Observation Network],
    [JAZZ],    [Jitter-Aware Zenith Zoomer],
    [KELP],    [Kernelized Ephemeral Latent Projector],
    [LUCID],   [Latent Uncertainty Calibration in Dreams],
    [MOSS],    [Manifold-Oriented Story Synthesizer],
    [NEST],    [Neural Ephemeris Smoothing Transformer],
    [ORBIT],   [Out-of-Range Bayesian Interpolation Toolkit],
    [PULSE],   [Probabilistic Unrolling for Liminal Signal Extraction],
    [QUILL],   [Querying Unlikely Inferences with Lattice Logic],
    [RUNE],    [Recursive Uncertainty Network Ensemble],
    [SONAR],   [Spectral Observation for Noisy Astral Readings],
    [TANGO],   [Tractable Approximate Narrator for Galactic Observations],
    [UMBRA],   [Uncertainty Modeling for Backlit Radiant Anomalies],
    [VINE],    [Variational Inference on Nested Estuaries],
    [WISP],    [Weakly Informed Signal Prior],
    [YAWN],    [Yet Another Waveform Normalizer],
    [ZEST],    [Zero-Entropy Surrogate Transformer],
)
